### ISSUE TITLE
Actividad 3- Erik Israel Cuevas Hernández 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-ErikCuevas03#1]
[cuadro comparativo-metodo científico..pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-ErikCuevas03/files/9474599/cuadro.comparativo-metodo.cientifico.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by josealfredo79** [comment]
Faltan las referencias

**Comment by josealfredo79** [comment]
Calificación 14

**Comment by josealfredo79** [comment]
Revisado..
